version: '3'

services:
  frontend:
    build: 
      dockerfile: frontend.dockerfile
    ports:
      - "80:80"
    # networks:
    #   - app_network
  backend:
    build: 
      dockerfile: backend.dockerfile
    # networks:
    #   - app_network
    ports:
      - "3001:3001"
# networks:
#   app_network: