FROM node:lts-alpine
WORKDIR /
COPY ./back/package*.json .
RUN npm install
COPY ./back/. .
ENV NODE_ENV=production
RUN npm run build
RUN npm install pm2 -g
EXPOSE 3001
VOLUME ./back/db ./db
CMD ["npm", "run", "pm2"]