FROM node:lts-alpine
WORKDIR /back
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
RUN npm install pm2 -g
EXPOSE 3001
VOLUME /back/db
ENV NODE_ENV=production
CMD ["npm", "run", "pm2"]


